# (4주차) 9월27일 -- draft
> 딥러닝의 기초 - 회귀분석(2)--step1~4, step 2,3,4의 다른표현

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

## step2의 다른버전: torch.nn.MSELoss()

yhat은 어떠한 방식으로든 만들었다고 가정하자. 

In [282]:
What = torch.tensor([[-5.0],[10.0]],requires_grad=True)
yhat = X@What

### ver1

In [287]:
loss_fn = torch.nn.MSELoss()

In [291]:
loss = loss_fn(y,yhat)
loss

tensor(85.8769, grad_fn=<MseLossBackward0>)

### 잘못된사용1 

In [299]:
_y = y.reshape(-1)
_y

tensor([-8.5420, -6.5767, -5.9496, -4.4794, -4.2516, -3.1326, -4.0239, -4.1862,
        -3.3403, -2.2027, -2.0262, -2.5619, -1.3353, -2.0466, -0.4664, -1.3513,
        -1.6472, -0.1089, -0.3071, -0.6299, -0.0438,  0.4163,  0.4166, -0.0943,
         0.2662,  0.4591,  0.8905,  0.8998,  0.6314,  1.3845,  0.8085,  1.2594,
         1.1211,  1.9232,  1.0619,  1.3552,  2.1161,  1.1437,  1.6245,  1.7639,
         1.6022,  1.7465,  0.9830,  1.7824,  2.1116,  2.8621,  2.1165,  1.5226,
         2.5572,  2.8361,  3.3956,  2.0679,  2.8140,  3.4852,  3.6059,  2.5966,
         2.8854,  3.9173,  3.6527,  4.1029,  4.3125,  3.4026,  3.2180,  4.5686,
         4.3772,  4.3075,  4.4895,  4.4827,  5.3170,  5.4987,  5.4632,  6.0328,
         5.2842,  5.0539,  5.4538,  6.0337,  5.7250,  5.7587,  6.2020,  6.5992,
         6.4621,  6.5140,  6.6846,  7.3497,  8.0909,  7.0794,  6.8667,  7.4229,
         7.2544,  7.1967,  9.5006,  9.0339,  7.4887,  9.0759, 11.0946, 10.3260,
        12.2665, 13.0983, 12.5468, 13.83

In [300]:
loss_fn(_y,yhat)

tensor([[135.5907, 126.2216, 123.2319,  ...,  32.4258,  35.0549,  28.9185],
        [126.2216, 120.7149, 118.9577,  ...,  65.5866,  67.1319,  63.5252],
        [123.2319, 118.9577, 117.5938,  ...,  76.1684,  77.3677,  74.5683],
        ...,
        [ 32.4258,  65.5866,  76.1684,  ..., 397.5638, 388.2584, 409.9775],
        [ 35.0549,  67.1319,  77.3677,  ..., 388.2584, 379.2573, 400.2664],
        [ 28.9185,  63.5252,  74.5683,  ..., 409.9775, 400.2664, 422.9326]],
       grad_fn=<DivBackward0>)

하여튼 shape을 조심해야함

## step3의 다른버전: 없어요 ㅎㅎ 

`-` 미분은 무조건 `loss.backward()`로 하면된다. 

`-` 그런데 step1에서 정의한 다른 방식들에 의해서 미분된값이 저장되는 루트는 다름 

### 예시1: 지난시간에 한거

In [339]:
What = torch.tensor([[-5.0],[10.0]],requires_grad=True)
yhat = X@What
loss = loss_fn(y,yhat) 
loss.backward() 

In [340]:
What.grad

tensor([[-13.4225],
        [ 11.8893]])

### 예시2: (ver1)

`-` net를 생성 

In [364]:
torch.manual_seed(43052)
net = torch.nn.Linear(in_features=1, out_features=1, bias=True) 

`-` net의 weight와 bias가 $y_i=\hat{w}x_i + \hat{b}=10x_i - 5$와 같이 되도록 설정 

In [365]:
net.weight # what = -0.3467 

Parameter containing:
tensor([[-0.3467]], requires_grad=True)

In [366]:
net.weight.data = torch.tensor([[10.00]]) 

In [367]:
net.weight # 이제 what = 10.00 

Parameter containing:
tensor([[10.]], requires_grad=True)

In [368]:
net.bias # 지금 bhat = -0.8470

Parameter containing:
tensor([-0.8470], requires_grad=True)

In [369]:
net.bias.data = torch.tensor([-5.0]) # 이제 bhat = -5.0

In [370]:
net.bias

Parameter containing:
tensor([-5.], requires_grad=True)

`-` yhat계산 $\to$ loss계산 $\to$ 미분 $\to$ 미분값확인 

In [371]:
yhat = net(x) 

In [372]:
loss = loss_fn(y,yhat) 
loss

tensor([[85.8769]], grad_fn=<DivBackward0>)

In [373]:
loss.backward()

In [376]:
net.bias.grad,net.weight.grad

(tensor([-13.4225]), tensor([[11.8893]]))

### 예시3: (ver2) 

`-` net를 생성 

In [377]:
torch.manual_seed(43052)
net = torch.nn.Linear(in_features=2, out_features=1, bias=False) 

`-` net의 weight와 bias가 $y_i=\hat{w}x_i + \hat{b}=10x_i - 5$와 같이 되도록 설정 

In [378]:
net.weight 

Parameter containing:
tensor([[-0.2451, -0.5989]], requires_grad=True)

In [379]:
net.weight.data = torch.tensor([[-5.00,10.00]]) 

In [381]:
net.weight 

Parameter containing:
tensor([[-5., 10.]], requires_grad=True)

`-` yhat계산 $\to$ loss계산 $\to$ 미분 $\to$ 미분값확인 

In [382]:
yhat = net(X) 

In [383]:
loss = loss_fn(y,yhat) 
loss

tensor([[85.8769]], grad_fn=<DivBackward0>)

In [384]:
loss.backward()

In [385]:
net.weight.grad

tensor([[-13.4225,  11.8893]])